// Code generated by ogen, DO NOT EDIT.
package order_v1

type CancelOrderRes interface {
	cancelOrderRes()
}

type GetOrderByUUIDRes interface {
	getOrderByUUIDRes()
}

type NewOrderRes interface {
	newOrderRes()
}

type PayOrderRes interface {
	payOrderRes()
}
