// Code generated by ogen, DO NOT EDIT.

package order_v1

// OperationName is the ogen operation name
type OperationName = string

const (
	CancelOrderOperation    OperationName = "CancelOrder"
	GetOrderByUUIDOperation OperationName = "GetOrderByUUID"
	NewOrderOperation       OperationName = "NewOrder"
	PayOrderOperation       OperationName = "PayOrder"
)
